# -*- coding: utf-8 -*-
"""PREPROCESADO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUUmw40WrPr0a1rlF8RweT-Zu6278oIT

# PREPROCESADO DE IMAGENES DE FONDO DE OJO
## Dependiendo del dataset, se debe aplicar 1 o 2 procesamientos.  

##-En datasets como APTOS-2019, las imagenes originales ya vienen con recorte de bordes negros innecesarios, en este caso sólo aplicamos Ben-Graham + resize (224x224).
##-En datasets como MESSIDOR o DDR, las imagenes venen con bordes negros amplios horizontales y verticales entonces conviene aplicar: Primero un recorte de bordes innecesarios o **cropping**, que quita los bordes sobrantes y deja centrada la retina, generalmente en un formato cuadrado.  Luego se aplica Ben-Graham + resize (224x224).

##*Se dejarán dos ejemplos de uso, uno con imagenes de muestra de APTOS 2019, que no requiere cropping y otro con imagenes de muestra de DDR que si requiere cropping*

##*Importación de librerías necesarias*
"""

#IMPORTACIÓN DE LIBRERIAS
import cv2
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

"""## EJEMPLO 1: CON IMAGENES DE APTOS 2019
### Se tienen algunas imagenes de muestra con su tamaño original en /content/drive/MyDrive/NOTEBOOKS_DR/MODELOS_PREENTRENADOS/APTOS_SAMPLES/

### la función load_ben_color() hace 2 cosas: resize de la imagen a 224x224, esta es la resolución que pide la mayoría de modelos preentrenados.  Luego aplica el preprocesado Ben Graham.  Los parámetros óptimos de la función ya están defnidos por prueba y error.

"""

#DEFINICIÓN DE LA FUNCIÓN DE PREPROCESAMIENTO DE BEN GRAHAM
#los parámetros óptimos son sigmaX=10.1, alpha=4.12, gamma=-4
#La función pide como parámetros la imagen a procesar y el sigmaX, regresa la imagen procesada
def load_ben_color(img, sigmaX=10.1 ):
    image = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (224, 224) , interpolation=cv2.INTER_CUBIC)   #resize a 224x224
    image=cv2.addWeighted ( image, 4.12, cv2.GaussianBlur( image , (0,0) , sigmaX) ,-4 ,128)  #preprocesado ben graham
    return image

#Ejemplo de uso
#Cargamos una imagen de prueba del dataset APTOS_2019
img = cv2.imread("/content/drive/MyDrive/NOTEBOOKS DR/MODELOS_PREENTRENADOS/APTOS_SAMPLES/1e1fb019710d.png")  # Carga en BGR
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)   #Pasamos de BGR A RGB, esto es sólo para la visualización de la imagen original
img_processed = load_ben_color(img, sigmaX=10.1)  #Llamamos a la función de preprocesado, acá usamos directamente la imagen (img) leída (en BGR)
img_processed_rgb = cv2.cvtColor(img_processed, cv2.COLOR_BGR2RGB)  #Pasamos el resultado a RGB, para visualización o para guardarla en disco

# Mostrar ambas imágenes usando matplotlib
plt.figure(figsize=(20, 10))

# Imagen sin procesar
plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title("Imagen sin procesar")
plt.axis("oN")

# Imagen procesada
plt.subplot(1, 2, 2)
plt.imshow(img_processed)
plt.title("img_processed")
plt.axis("on")


plt.show()

"""## EJEMPLO 2: CON IMAGENES DE DDR dataset
### Se tienen algunas imagenes de muestra con su tamaño original en /content/drive/MyDrive/NOTEBOOKS_DR/MODELOS_PREENTRENADOS/DDR_SAMPLES/

### lA función crop_img toma una imagen, calcula el mejor círculo y hace el cropping de las áreas negras innecesarias al rededor de la retina.

### la función load_ben_color() hace 3 cosas: llama a crop_img para recortar bordes innecesarios, hace resize de la imagen a 224x224, esta es la resolución que pide la mayoría de modelos preentrenados.  Luego aplica el preprocesado Ben Graham.  Los parámetros óptimos de la función ya están defnidos por prueba y error.


"""

#RECORTE (CROPPING) DE BORDES NEGROS INNECESARIOS, DEJA LA IMAGEN CUADRADA Y CENTRADA EN LA ZONA DE INTERÉS
#función para extraer los parámetros el contorno cicular de la imagen
def crop_img(img):
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  #a escala de grises
    (t,thres) = cv2.threshold(img_gray, 10, 255, cv2.THRESH_BINARY) #aplicamos threshold para quedarnos con la mascara
    mask = cv2.medianBlur(thres,5)  #filtramos

    #detectamos círculo con hough, de ahí extremos el radio
    circ=cv2.HoughCircles(mask, cv2.HOUGH_GRADIENT,3,40, param1=50,param2=30,minRadius=500,maxRadius=2000)
    c = circ[0][0]   #el mejor circulo
    rad = int(c[2])
    cx = int(c[0])
    cy = int(c[1])
    img_crop = img[max(0, cy - rad) : max(0, cy + rad), max(0,cx - rad): max(0,cx + rad)]

    return img_crop

#PRUEBA VISUAL DE CROPPING
# ESTO SÓLO ES PARA VER LA DIFERENCIA ENTRE LA IMAGEN ORIGINAL Y LA IMAGEN RECORTADA Y CENTRADA, PERO EN LA PRÁCTICA
#LLAMAREMOS A LA FUNCIÓN crop_img DENTRO DE LA FUNCIÓN DE PREPROCESADO PARA HACER TODO EN UN SOLO PASO, ES DECIR,
#TOMAR LA IMAGEN ORIGINAL DEL DATASET, Y QUE EN UN SOLO LLAMADO SE HAGA CROPPING, RESIZE Y PREPROCESADO

img = cv2.imread("/content/drive/MyDrive/NOTEBOOKS DR/MODELOS_PREENTRENADOS/DDR_SAMPLES/007-5429-300.jpg")


img_crop = crop_img(img)   #recortar y redimensionar la imagen


# Crear figura con dos subplots
plt.figure(figsize=(12, 5))

# Imagen original
plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))  #  BGR → RGB para visualización
plt.title("Imagen original")
plt.axis('off')

#Imagen recortada
plt.subplot(1, 2, 2)
plt.imshow(cv2.cvtColor(img_crop, cv2.COLOR_BGR2RGB))           # normalmente las máscaras se ven mejor en escala de grises
plt.title("imagen recortada")
plt.axis('off')

plt.tight_layout()
plt.show()

#DEFINICIÓN DE LA FUNCIÓN DE PREPROCESAMIENTO DE BEN GRAHAM
#los parámetros óptimos son sigmaX=10.1, alpha=4.12, gamma=-4
#La función pide como parámetros la imagen a procesar y el sigmaX, regresa la imagen procesada
def load_crop_ben_color(img, sigmaX=10.1 ):
    image = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    image = crop_img(image)   # HACEMOS CROPPING A LA IMAGEN ORIGINAL PARA RECORTAR BORDES INNECESARIOS
    image = cv2.resize(image, (224, 224) , interpolation=cv2.INTER_CUBIC)   #resize a 224x224
    image=cv2.addWeighted ( image, 4.12, cv2.GaussianBlur( image , (0,0) , sigmaX) ,-4 ,128)  #preprocesado ben graham
    return image

#EJEMPLO DE APLICACIÓN, SE TOMA LA IMAGEN ORIGINAL DE DDR, SE LLAMA A load_crop_ben_color, ahora esta función hace el cropping a la imagen, la escala a 224x224 y la procesa

img = cv2.imread("/content/drive/MyDrive/NOTEBOOKS DR/MODELOS_PREENTRENADOS/DDR_SAMPLES/007-5429-300.jpg")  # Carga en BGR
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)    #Convertimos a RGB sólo para visualización de la imagen original
img_processed = load_crop_ben_color(img, sigmaX=10.1)    #llamamos a la función que hace recorte, resize y procesado
img_processed_rgb = cv2.cvtColor(img_processed, cv2.COLOR_BGR2RGB)   #Convertimos a RGB SÓLO para visualización o guardado en disco

# Mostrar ambas imágenes usando matplotlib
plt.figure(figsize=(20, 10))

# Imagen sin procesar
plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title("Imagen sin procesar")
plt.axis("oN")

# Imagen procesada
plt.subplot(1, 2, 2)
plt.imshow(img_processed)
plt.title("imgagen procesada")
plt.axis("on")


plt.show()